"use client";
import { useState } from "react";
import { Building2, Filter } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminUI";
import { adminRequests } from "@/lib/admin-data";

export default function AdminRequestsPage() {
  const [requests, setRequests] = useState(adminRequests);
  const [selected, setSelected] = useState<(typeof adminRequests)[number] | null>(null);

  return <AdminShell>
    <div className="mb-4 flex items-start justify-between"><div><h1 className="text-6xl font-semibold">Demandes d’inscription</h1><p className="text-[34px] text-slate-600">Examinez et validez les nouvelles demandes d’inscription des restaurants.</p></div><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-[34px]"> <Filter className="mr-2 inline h-4 w-4"/>Filtrer</button></div>
    <div className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[32px] text-slate-500">En attente</p><p className="text-6xl font-semibold">3</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-[32px] text-amber-700">À relancer</p><p className="text-6xl font-semibold text-amber-700">1</p></div></div>
    <div className="space-y-3">{requests.map((r)=><div key={r.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.06)]"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="mt-1 rounded-full bg-emerald-100 p-2 text-emerald-600"><Building2 className="h-4 w-4"/></span><div><p className="text-5xl font-semibold">{r.restaurant}</p><p className="text-[33px] text-slate-600">{r.owner} • {r.city}</p><p className="text-[33px] text-slate-600">{r.phone} • {r.email}</p><p className="text-[31px] text-slate-500">{r.type} • {r.source}</p></div></div><div className="text-right"><p className="text-[31px] text-slate-500">{r.date}</p><div className="mt-4 flex gap-2"><button onClick={()=>setSelected(r)} className="rounded-xl bg-emerald-600 px-3 py-2 text-[32px] text-white">Examiner</button><button onClick={()=>setRequests((p)=>p.filter((x)=>x.id!==r.id))} className="rounded-xl border border-slate-200 px-3 py-2 text-[32px]">Refuser</button></div></div></div></div>)}</div>

    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white p-6"><h3 className="text-5xl font-semibold">Valider la demande</h3><p className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-[31px]">Vous allez créer le compte de <strong>{selected.restaurant}</strong>. Les accès seront envoyés automatiquement au propriétaire.</p><div className="mt-4 grid gap-3"><select className="rounded-xl border border-slate-200 px-3 py-2 text-[32px]"><option>Type d’abonnement: Essai gratuit</option><option>Standard</option><option>Premium</option></select><select className="rounded-xl border border-slate-200 px-3 py-2 text-[32px]"><option>Durée d’essai: 14 jours</option><option>7 jours</option><option>30 jours</option></select><textarea className="rounded-xl border border-slate-200 px-3 py-2 text-[32px]" rows={3} placeholder="Ajouter une note interne..." /><label className="text-[32px]"><input type="checkbox" defaultChecked className="mr-2"/>Email</label><label className="text-[32px]"><input type="checkbox" defaultChecked className="mr-2"/>SMS</label><label className="text-[32px]"><input type="checkbox" defaultChecked className="mr-2"/>WhatsApp</label><p className="rounded-xl bg-violet-50 p-3 text-[30px] text-violet-700">Un message personnalisé sera envoyé avec les identifiants et les liens de démarrage rapide.</p></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setSelected(null)} className="rounded-xl border px-4 py-2 text-[32px]">Annuler</button><button onClick={()=>{setRequests((p)=>p.filter((x)=>x.id!==selected.id));setSelected(null);}} className="rounded-xl bg-emerald-600 px-4 py-2 text-[32px] text-white">Créer le compte</button></div></div></div>}
  </AdminShell>;
}
