"use client";
import Link from "next/link";
import { MoreVertical, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin/AdminUI";
import { adminRestaurants } from "@/lib/admin-data";

export default function AdminRestaurantsPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Tous les statuts");
  const filtered = useMemo(() => adminRestaurants.filter((r) => (status === "Tous les statuts" || r.status === status) && `${r.name} ${r.owner} ${r.city}`.toLowerCase().includes(query.toLowerCase())), [query, status]);

  return <AdminShell>
    <h1 className="text-6xl font-semibold">Restaurants</h1><p className="text-[34px] text-slate-600">Gérez votre réseau de restaurants.</p>
    <div className="mt-4 grid grid-cols-3 gap-3">{[["Actifs", "48"], ["Essai gratuit", "12"], ["Suspendus", "3"]].map(([l,v])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[31px] text-slate-500">{l}</p><p className="text-6xl font-semibold">{v}</p></div>)}</div>
    <div className="mt-4 rounded-2xl border border-slate-200 bg-white p-3"><div className="grid grid-cols-5 gap-2"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-[30px]" placeholder="Rechercher..."/></div><select className="rounded-xl border border-slate-200 px-3 text-[30px]" value={status} onChange={(e)=>setStatus(e.target.value)}><option>Tous les statuts</option><option>Actif</option><option>Essai gratuit</option><option>Suspendu</option></select><select className="rounded-xl border border-slate-200 px-3 text-[30px]"><option>Toutes les villes</option></select><select className="rounded-xl border border-slate-200 px-3 text-[30px]"><option>Tous les abonnements</option></select><button className="rounded-xl border border-slate-200 px-3 text-[30px]">Réinitialiser</button></div></div>
    <div className="mt-3 space-y-3">{filtered.map((r, i)=><div key={r.id} className={`rounded-2xl border bg-white p-3 ${i===0?"border-emerald-300":"border-slate-200"}`}><div className="grid grid-cols-[1.2fr_1fr_1.3fr_1.5fr_1.2fr_1fr_1fr_1fr_auto_auto_auto] items-center gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 text-emerald-700">{r.name.slice(0,2).toUpperCase()}</span><div><p className="text-[34px] font-semibold">{r.name}</p><p className="text-[28px] text-slate-500">{r.status}</p></div></div><div><p className="text-[32px]">{r.owner}</p><p className="text-[28px] text-slate-500">{r.city}</p></div><div><p className="text-[32px]">{r.phone}</p><p className="text-[28px] text-slate-500">{r.email}</p></div><div><p className="text-[32px]">{r.plan}</p><p className="text-[28px] text-slate-500">{r.priceOrTrial}</p></div><p className="text-[31px]">{r.lastActivity}</p><div><p className="text-[40px] font-semibold">{r.ordersToday}</p><p className="text-[26px] text-emerald-600">{r.ordersTrend ?? "-"}</p></div><div><p className="text-[40px] font-semibold">{r.scansToday}</p><p className="text-[26px] text-emerald-600">{r.scansTrend ?? "-"}</p></div><Link href={`/admin/restaurants/${r.id}`} className="rounded-xl border border-slate-200 px-3 py-2 text-[28px]">Voir la fiche</Link><button className="rounded-xl border border-slate-200 px-3 py-2 text-[28px]">{r.status === "Suspendu" ? "Réactiver" : "Suspendre"}</button><button className="rounded-xl border border-slate-200 p-2"><MoreVertical className="h-4 w-4"/></button></div></div>)}</div>
    <div className="mt-3 flex justify-end gap-2 text-[28px]"><button className="rounded-lg border px-3 py-1">Précédent</button><button className="rounded-lg border border-emerald-500 bg-emerald-50 px-3 py-1">1</button><button className="rounded-lg border px-3 py-1">2</button><button className="rounded-lg border px-3 py-1">Suivant</button></div>
  </AdminShell>;
}
